# Generated by Django 4.2.7 on 2023-11-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("cur_code", models.CharField(max_length=3)),
                (
                    "cur_official_rate",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
            ],
            options={
                "unique_together": {("date", "cur_code")},
            },
        ),
    ]
